const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const staged = path.join(__dirname, '../friendship-content.js');
const source = fs.readFileSync(fs.existsSync(staged) ? staged : path.join(__dirname, '../content.js'), 'utf8');
const start = source.indexOf('  const enhancedProfileFriendshipRequests =');
const end = source.indexOf('  function makeEnhancedProfileHeaderDetails(', start);
const makeNode = (tag) => ({tag,style:{},dataset:{},children:[],append(...nodes){this.children.push(...nodes)}});
const context = {Intl,Date,chrome:{runtime:{sendMessage(message,cb){cb({ok:true,seconds:1735689600})}}},
  isFeatureEnabled:()=>false,isEnhancedProfileFeatureEnabled:()=>true,
  getEnhancedProfileViewerUserId:()=>1,getRobloxPageLocale:()=> 'de-DE',
  makeEnhancedProfileElement:makeNode,document:{createElement:makeNode}};
vm.createContext(context);
vm.runInContext(source.slice(start,end),context);
(async()=>{
  let inserted;
  const identity = {isConnected:true,querySelector(selector){assert.equal(selector,'.rtp-username');return {after(row){inserted=row}}}};
  context.appendEnhancedProfileFriendship(identity,42,1);
  await new Promise(resolve=>setImmediate(resolve));
  assert.equal(inserted.children[0],'Befreundet seit ');
  assert.equal(inserted.children[1].dateTime,'2025-01-01T00:00:00.000Z');
  inserted=null;
  identity.isConnected=false;
  context.appendEnhancedProfileFriendship(identity,42,1);
  await new Promise(resolve=>setImmediate(resolve));
  assert.equal(inserted,null);
  identity.isConnected=true;
  context.chrome.runtime.sendMessage=(message,cb)=>cb({ok:true,seconds:null,mutualCount:15});
  context.formatEnhancedProfileNumber=String;
  context.getEnhancedProfileUiText=()=> 'Mutuals';
  const social={isConnected:true,children:[],querySelector(){return this.children[0] || null},append(node){this.children.push(node)}};
  context.appendEnhancedProfileFriendship(identity,43,1,social,true);
  await new Promise(resolve=>setImmediate(resolve));
  assert.equal(social.children.length,1);
  context.isFeatureEnabled=()=>true;
  context.chrome.runtime.sendMessage=(message,cb)=>{assert.equal(message.includeRegion,true);cb({ok:true,regionCode:'DE',seconds:null})};
  let diagnostic;
  const developerIdentity={isConnected:true,querySelector(){return null},append(node){diagnostic=node}};
  context.appendEnhancedProfileFriendship(developerIdentity,44,1);
  await new Promise(resolve=>setImmediate(resolve));
  assert.ok(diagnostic.textContent.includes('Deutschland (DE)'));
  context.chrome.runtime.sendMessage=(message,cb)=>cb({ok:true,regionCode:null});
  context.appendEnhancedProfileFriendship(developerIdentity,45,1);
  await new Promise(resolve=>setImmediate(resolve));
  assert.ok(diagnostic.textContent.includes('Keine Regionsangabe verfügbar'));
  context.chrome.runtime.sendMessage=(message,cb)=>cb({ok:false});
  context.appendEnhancedProfileFriendship(developerIdentity,46,1);
  await new Promise(resolve=>setImmediate(resolve));
  assert.ok(diagnostic.textContent.includes('API-Anfrage fehlgeschlagen'));
  context.isFeatureEnabled=()=>false;
  assert.equal(social.children[0].tag,'span');
  assert.equal(social.children[0].href,undefined);
  assert.equal(inserted,null);
  context.appendEnhancedProfileFriendship(identity,43,1,social,true);
  await new Promise(resolve=>setImmediate(resolve));
  assert.equal(social.children.length,1);
  assert.ok(!source.includes('appendEnhancedProfileFriendship(grid, identity.userId'));
  console.log('Friendship placement below username, localized date and detached profile guard: PASS');
})().catch(error=>{console.error(error);process.exitCode=1});
